{% set version = "4-0b8cc" %}
{% set sha256 = "d1b550f1cd2a3de6ba569c8badbabf1a7f88529913e0bdbf2d8d53e94beb6b93" %}

package:
  name: mmseqs2
  version: {{ version|replace("-", ".")  }}

build:
  number: 1

source:
  url: https://github.com/soedinglab/mmseqs2/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - openmp
    - perl
    - gawk
    - zlib
    - bzip2

  run:
    - openmp
    - gawk
    - zlib
    - bzip2

test:
  commands:
    - mmseqs > /dev/null

about:
  home: https://github.com/soedinglab/mmseqs2
  license: GPLv3
  summary: "MMseqs2.0: ultra fast and sensitive protein search and clustering suite"
